### ISSUE TITLE
`yarn dev` errors out when `optimizeFonts` is turned on

### ISSUE THREAD

**Issue by jackhsu978** [ritz078/raaga#106]
Running `yarn dev` exits with the following error message after https://github.com/ritz078/raaga/pull/98 was merged:

```sh
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

{ Error: Cannot find module '/Users/jackhsu/code/raaga/.next/serverless/font-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireFontManifest (/Users/jackhsu/code/raaga/node_modules/next/dist/next-server/server/require.js:2:553)
    at new Server (/Users/jackhsu/code/raaga/node_modules/next/dist/next-server/server/next-server.js:3:699)
    at new DevServer (/Users/jackhsu/code/raaga/node_modules/next/dist/server/next-dev-server.js:1:3026)
    at createServer (/Users/jackhsu/code/raaga/node_modules/next/dist/server/next.js:2:607)
    at start (/Users/jackhsu/code/raaga/node_modules/next/dist/server/lib/start-server.js:1:385)
    at nextDev (/Users/jackhsu/code/raaga/node_modules/next/dist/cli/next-dev.js:21:279) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
```

I check the file `.next/serverless/font-manifest.json` and it does not exist.

If I turn `optimizeFonts` to `false`, it would work.

**Comment by ritz078** [comment]
@prateekbh I am facing the same issue. Can you please look into this ?

**Comment by prateekbh** [comment]
This makes sense, I can PR that only enables the flag when doing production build

**Comment by prateekbh** [comment]
PR on the way! thanks for reporting this
